# Generated by Django 3.0.5 on 2020-08-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
