# Generated by Django 3.0.5 on 2020-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200831_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
